In [1]:
from google.colab import files
uploaded = files.upload()      # uoloading a csv file

Saving StudentPerformance_1000.csv to StudentPerformance_1000.csv

In [3]:
import pandas as pd
df = pd.read_csv("StudentPerformance_1000.csv")
df.head(50)

,gender,race/ethnicity,parental level of education,lunch,test preparation course,math score,reading score,writing score
0,female,group C,master's degree,free/reduced,none,80,56,93
1,female,group E,bachelor's degree,standard,none,37,45,45
2,male,group E,bachelor's degree,standard,completed,84,81,32
3,male,group C,some high school,standard,completed,58,90,85
4,female,group E,high school,free/reduced,none,47,27,18
5,male,group C,associate's degree,standard,none,92,44,95
6,male,group D,associate's degree,standard,none,61,78,0
7,female,group B,master's degree,free/reduced,completed,64,63,20
8,male,group C,high school,free/reduced,completed,57,30,5
9,male,group B,bachelor's degree,standard,completed,12,51,44
10,female,group A,high school,standard,completed,72,90,58
11,female,group D,master's degree,standard,completed,13,37,47
12,female,group B,some high school,free/reduced,none,5,59,45
13,male,group E,associate's degree,standard,completed,90,24,58
14,male,group D,master's degree,standard,completed,44,42,19
15,male,group E,master's degree,free/reduced,completed,46,37,15
16,female,group A,master's degree,free/reduced,none,94,61,65
17,female,group B,master's degree,free/reduced,completed,39,98,23
18,female,group E,bachelor's degree,free/reduced,none,48,60,26
19,male,group E,bachelor's degree,free/reduced,none,39,84,56
20,male,group A,bachelor's degree,free/reduced,completed,82,87,87
21,male,group D,bachelor's degree,free/reduced,completed,98,76,15
22,male,group E,master's degree,standard,none,65,79,79
23,female,group B,bachelor's degree,standard,completed,59,63,25
24,male,group E,associate's degree,standard,none,96,63,44
25,female,group A,master's degree,free/reduced,none,80,41,75
26,male,group C,bachelor's degree,free/reduced,completed,27,33,47
27,female,group C,master's degree,free/reduced,none,94,63,98
28,male,group B,high school,free/reduced,none,66,77,10
29,male,group A,master's degree,free/reduced,completed,20,0,74
30,female,group E,master's degree,free/reduced,none,47,31,40
31,female,group B,master's degree,standard,completed,71,100,23
32,male,group A,bachelor's degree,free/reduced,none,70,8,27
33,male,group A,some high school,free/reduced,none,79,20,75
34,male,group B,high school,free/reduced,none,53,41,29
35,female,group A,bachelor's degree,free/reduced,completed,89,58,77
36,male,group E,high school,standard,none,64,1,68
37,female,group B,bachelor's degree,free/reduced,completed,32,50,54
38,male,group B,some high school,free/reduced,completed,57,100,51
39,female,group B,high school,free/reduced,completed,15,3,92
40,female,group B,associate's degree,free/reduced,completed,81,89,58
41,male,group E,master's degree,standard,none,95,60,94
42,female,group D,associate's degree,standard,completed,33,71,58
43,female,group C,bachelor's degree,standard,none,78,51,64
44,female,group D,bachelor's degree,standard,none,10,75,39
45,female,group A,master's degree,standard,completed,35,71,42
46,male,group A,high school,free/reduced,none,72,41,29
47,male,group A,high school,free/reduced,none,85,2,78
48,male,group A,associate's degree,standard,completed,48,56,24
49,female,group B,master's degree,standard,none,83,40,41

In [8]:
df["total_score"] = df["math score"] + df["reading score"] + df["writing score"]  #addition
df[["math score", "reading score", "writing score", "total_score"]]

     math score  reading score  writing score  total_score
0            80             56             93          229
1            37             45             45          127
2            84             81             32          197
3            58             90             85          233
4            47             27             18           92
..          ...            ...            ...          ...
995           7             90             47          144
996          35             46             41          122
997          46             42             15          103
998          56             47             28          131
999          23              4             14           41

[1000 rows x 4 columns]

In [5]:
df["average_score"] = df["total_score"] / 3  #division
df[["total_score", "average_score"]].head()

   total_score  average_score
0          229      76.333333
1          127      42.333333
2          197      65.666667
3          233      77.666667
4           92      30.666667

In [6]:
df["math_reading_diff"] = df["math score"] - df["reading score"]  #sub
df[["math score", "reading score", "math_reading_diff"]].head()

   math score  reading score  math_reading_diff
0          80             56                 24
1          37             45                 -8
2          84             81                  3
3          58             90                -32
4          47             27                 20

In [7]:
df["math_pass"] = df["math score"] >= 40    #boolean
df[["math score", "math_pass"]].head()

   math score  math_pass
0          80       True
1          37      False
2          84       True
3          58       True
4          47       True

In [9]:
df["mul_weighted_score"] = (df["math score"] * 1.5) + (df["reading score"] * 1.5) + (df["writing score"] * 1.5) #mul
df[["math score", "reading score", "writing score", "mul_weighted_score"]].head()

   math score  reading score  writing score  mul_weighted_score
0          80             56             93               343.5
1          37             45             45               190.5
2          84             81             32               295.5
3          58             90             85               349.5
4          47             27             18               138.0

In [1]:
#operators
x, y = 10, 20
print('Arithmetic:', x + y)
print('Comparison:', x < y)
print('Logical:', x < y and y > 15)
x += 5
print('Assignment:', x)
print('Membership:', 10 in [10, 20])
print('Identity:', x is y)

Arithmetic: 30
Comparison: True
Logical: True
Assignment: 15
Membership: True
Identity: False

In [2]:
#conditional statements
def score_category(score):
    if score >= 90:
        return "Excellent"
    elif score >= 60:
        return "Good"
    else:
        return "Needs Improvement"
print(score_category(75))

Good

In [3]:
#loops
for_loop_result = []
for score in [80, 50, 30]:
    if score < 40:
        break
    for_loop_result.append(score)
print('For loop:', for_loop_result)

while_loop_result = []
i = 0
while i < 3:
    while_loop_result.append(i)
    i += 1
print('While loop:', while_loop_result)

For loop: [80, 50]
While loop: [0, 1, 2]

In [4]:
#  Algorithm - Average score
def average_score(math, read, write):
    return (math + read + write) / 3
print('Average:', average_score(80, 70, 90))

Average: 80.0

In [5]:
#  Functions & Arguments
def greet(name, score=50):
    return f"{name} scored {score}"
print(greet("Deepika"))
print(greet("Meghana", 85))

Deepika scored 50
Meghana scored 85

In [7]:
# Lists, Tuples, Sets, Dictionaries
my_list = [1, 2, 3]
my_tuple = (4, 5, 6)
my_set = {1, 2, 2, 3}
my_dict = {"name": "Asha", "score": 90}

In [8]:
#  Dictionary operations
print(my_dict.keys())
print(my_dict.values())
my_dict["grade"] = 'A'
print(my_dict)

dict_keys(['name', 'score'])
dict_values(['Asha', 90])
{'name': 'Asha', 'score': 90, 'grade': 'A'}

In [9]:
#  Data Type Properties
print('List duplicates:', [1, 2, 2])
print('Tuple immutable:', (3, 4, 4))
print('Set unique:', {1, 1, 2})

List duplicates: [1, 2, 2]
Tuple immutable: (3, 4, 4)
Set unique: {1, 2}

In [10]:
#  String indexing and slicing
text = "Python"
print('First letter:', text[0])
print('Slicing:', text[1:4])

First letter: P
Slicing: yth

In [11]:
# List & Tuple Indexing/Slicing
print('List index:', my_list[1])
print('Tuple slice:', my_tuple[1:])

List index: 2
Tuple slice: (5, 6)

In [12]:
# Sorting
unsorted = [3, 1, 4, 2]
print('Sorted:', sorted(unsorted))

Sorted: [1, 2, 3, 4]

In [13]:
# Set Operations
a = {1, 2, 3}
b = {3, 4, 5}
print('Union:', a | b)
print('Intersection:', a & b)
print('Difference:', a - b)

Union: {1, 2, 3, 4, 5}
Intersection: {3}
Difference: {1, 2}

In [14]:
# Lambda: filter, map, reduce
from functools import reduce
nums = [10, 25, 30, 45]
print('Filter >20:', list(filter(lambda x: x > 20, nums)))
print('Map +5:', list(map(lambda x: x + 5, nums)))
print('Reduce sum:', reduce(lambda a, b: a + b, nums))

Filter >20: [25, 30, 45]
Map +5: [15, 30, 35, 50]
Reduce sum: 110

In [15]:
# File handling
with open("logfile.txt", "a") as f:
    f.write("Logged student data.\n")

In [16]:
# Docstring
def multiply(a, b):
    """Returns the product of a and b"""
    return a * b
print('Multiply:', multiply(4, 5))

Multiply: 20

In [17]:
scores = [70, 80, 50]
print(scores[1:])     # slicing
print(scores[0])      # indexing
print(sorted(scores)) # sorting

[80, 50]
70
[50, 70, 80]

In [19]:
#dictionary operations
student = {'name': 'Asha', 'score': 85}
print(student['score'])  # access
student['grade'] = 'A'   # add

85

In [24]:
import pandas as pd
from functools import reduce

# Sample Data (add more rows or load from file if needed)
data = {
    "math score": [80, 37, 84, 58, 47],
    "reading score": [56, 45, 81, 90, 27],
    "writing score": [93, 45, 32, 85, 18]
}

df = pd.DataFrame(data)
# Lambda with filter: Get passing students (math score > 50)
passing = list(filter(lambda x: x > 50, df['math score']))
print("Passing Math Scores:", passing)

# Lambda with map: Increase reading score by 5
updated_reading = list(map(lambda x: x + 5, df['reading score']))
print("Updated Reading Scores:", updated_reading)

# Lambda with reduce: Total writing score
total_writing = reduce(lambda a, b: a + b, df['writing score'])
print("Total Writing Score:", total_writing)

Passing Math Scores: [80, 84, 58]
Updated Reading Scores: [61, 50, 86, 95, 32]
Total Writing Score: 273

In [25]:
# top orders from the restaurant
orders = {'Pizza': 120, 'Burger': 75, 'Fries': 150, 'Salad': 40}
top_item = max(orders, key=orders.get)
print(f"Top ordered item: {top_item}")

Top ordered item: Fries

In [26]:
#parameters and arguments
def greet(name):  # name is parameter
    print("Hello", name)

greet("Deepika")  # "Deepika" is argument

Hello Deepika

In [27]:
#functions
def average_score(math, reading, writing):
    return (math + reading + writing) / 3

In [28]:
#loop
for score in df['math score']:
    if score < 40:
        break

In [29]:
df['math score'] > 50  # Comparison operator

0     True
1    False
2     True
3     True
4    False
Name: math score, dtype: bool